### ISSUE TITLE
Make Travis CI green

### ISSUE THREAD

**Issue by piroor** [droonga/droonga-engine#34]
On my environment `bundle exec rake test` successes but it fails on Travis CI...

Diff of dependencies:

~~~
--- local-bundle.txt	2015-03-18 14:38:53.906016114 +0900
+++ travis-ci-bundle.txt	2015-03-18 14:37:50.710013918 +0900
@@ -1,6 +1,6 @@
 rake 10.4.2
 archive-zip 0.7.0
-bundler 1.8.5
+bundler 1.7.6
 CFPropertyList 2.2.8
 cool.io 1.3.0
 drnbench 1.0.5
@@ -9,35 +9,34 @@
 droonga-client 0.2.1
 droonga-engine 1.1.0
 droonga-message-pack-packer 1.0.3
-facter 2.4.1
+facter 2.3.0
 faraday 0.9.1
 faraday_middleware 0.9.1
-fluent-logger 0.5.0
+fluent-logger 0.4.10
 gettext 3.1.6
 gqtp 1.0.6
 grn2drn 1.0.5
 groonga-client 0.1.0
-groonga-command 1.0.8
-groonga-command-parser 1.0.2
+groonga-command 1.1.0
+groonga-command-parser 1.0.4
 io-like 0.3.0
 json 1.8.2
-kramdown 1.6.0
+kramdown 1.5.0
 locale 2.1.0
-msgpack 0.5.11
+msgpack 0.5.10
 multipart-post 2.0.0
 packnga 1.0.1
 pkg-config 1.1.6
-power_assert 0.2.3
+power_assert 0.2.2
 rack 1.6.0
 rr 1.1.2
-rroonga 4.0.4
+rroonga 4.0.9
 sigdump 0.2.2
 slop 3.6.0
-sys-proctable 0.9.6
+sys-proctable 0.9.4
 test-unit 3.0.9
 test-unit-notify 1.0.4
 test-unit-rr 1.0.3
 text 1.3.0
 yajl-ruby 1.2.1
 yard 0.8.7.6
-
~~~

**Comment by piroor** [comment]
I've updated my local rroonga from 4.0.4 to 5.0.1, with following steps:

~~~
$ cd ../rroonga
$ bundle exec rake compile
$ cd ../droonga-engine/
$ bundle update
~~~

**Comment by piroor** [comment]
Still successes on my local environment. Hmm...

**Comment by kou** [comment]
Is `DEFAULT_TEST_TASK=test:command:default rake test` succeeded?

**Comment by piroor** [comment]
I've updated both groonga-command and groonga-command-parser also. And now retrying with `DEFAULT_TEST_TASK=test:command:default bundle exec rake test`.

**Comment by piroor** [comment]
I read deatils of both failed results https://travis-ci.org/droonga/droonga-engine/jobs/47891553 and https://travis-ci.org/droonga/droonga-engine/jobs/47891554 and there seems to be random failure.

**Comment by piroor** [comment]
Updated diff

~~~
--- local-bundle.txt	2015-03-18 17:06:19.118323484 +0900
+++ travis-ci-bundle.txt	2015-03-18 17:04:53.950320525 +0900
@@ -1,7 +1,6 @@
-rake 10.4.2
-archive-zip 0.7.0
-bundler 1.8.5
 CFPropertyList 2.2.8
+archive-zip 0.7.0
+bundler 1.7.6
 cool.io 1.3.0
 drnbench 1.0.5
 drndump 1.0.0
@@ -29,6 +28,7 @@
 pkg-config 1.1.6
 power_assert 0.2.3
 rack 1.6.0
+rake 10.4.2
 rr 1.1.2
 rroonga 5.0.1
 sigdump 0.2.2
~~~

**Comment by piroor** [comment]
Comparison of results for completely same codes:

 * [Build #1098 - droonga/droonga-engine - Travis CI](https://travis-ci.org/droonga/droonga-engine/builds/47891213 "Build #1098 - droonga/droonga-engine - Travis CI")
   * All unit tests are succeeded.
   * Ruby 1.9.3 test:command:default [stalled]
   * Ruby: 2.0.0 test:command:default [stalled]
   * Ruby: 2.1.0 test:command:default [stalled]
   * Ruby: 2.2.0 test:command:default [stalled]
   * Ruby 1.9.3 test:command:version1 [succeeded] 
   * Ruby: 2.0.0 test:command:version1 [failed / 5 failures]
   * Ruby: 2.1.0 test:command:version1 [failed / 4 failures]
   * Ruby: 2.2.0 test:command:version1 [failed / 9 failures]
 * [Build #1101 - droonga/droonga-engine - Travis CI](https://travis-ci.org/droonga/droonga-engine/builds/54832627 "Build #1101 - droonga/droonga-engine - Travis CI")
   * All unit tests are succeeded.
   * Ruby 1.9.3 test:command:default [failed / 1 failure] - different from previous result
   * Ruby: 2.0.0 test:command:default [stalled]
   * Ruby: 2.1.0 test:command:default [stalled]
   * Ruby: 2.2.0 test:command:default [stalled]
   * Ruby 1.9.3 test:command:version1 [succeeded]
   * Ruby: 2.0.0 test:command:version1 [succeeded] - different from previous result
   * Ruby: 2.1.0 test:command:version1 [failed / 9 failures] - different from previous result
   * Ruby: 2.2.0 test:command:version1 [failed / 1 failures] - different from previous result

**Comment by kou** [comment]
Can we drop command version 1?

**Comment by piroor** [comment]
Build #1101, Ruby 1.9.3 test:command:default [failed / 1 failure]

Failed test:

~~~
groonga/table_create/dat-without-key-type.test: 2015-03-18T08:01:02+00:00[9673][error]: serf-agent[9685]: memberlist: Failed to receive remote state: EOF
2015-03-18T08:01:03+00:00[9688][error]: dispatcher: no steps error: id=127.0.0.1:60023/droonga.#0, message={"id"=>"127.0.0.1:60023/droonga.#0", "input"=>"errors", "value"=>nil}
2015-03-18T08:01:03+00:00[9688][error]: dispatcher: no steps error: id=127.0.0.1:60023/droonga.#0, message={"id"=>"127.0.0.1:60023/droonga.#0", "input"=>"result", "value"=>[[-22, 1426665663.363337, 0.0001239776611328125, "key_type is required for TABLE_DAT_KEY table"], false]}
2015-03-18T08:01:03+00:00[9688][error]: dispatcher: no steps error: id=127.0.0.1:60023/droonga.#0, message={"id"=>"127.0.0.1:60023/droonga.#0", "input"=>"errors", "value"=>nil}
2015-03-18T08:01:03+00:00[9688][error]: dispatcher: no steps error: id=127.0.0.1:60023/droonga.#0, message={"id"=>"127.0.0.1:60023/droonga.#0", "input"=>"result", "value"=>[[-22, 1426665663.364075, 0.00013685226440429688, "key_type is required for TABLE_DAT_KEY table"], false]}
2015-03-18T08:01:03+00:00[9688][error]: dispatcher: no steps error: id=127.0.0.1:60023/droonga.#0, message={"id"=>"127.0.0.1:60023/droonga.#0", "input"=>"errors", "value"=>nil}
2015-03-18T08:01:03+00:00[9688][error]: dispatcher: no steps error: id=127.0.0.1:60023/droonga.#0, message={"id"=>"127.0.0.1:60023/droonga.#0", "input"=>"result", "value"=>[[-22, 1426665663.3644688, 0.00011372566223144531, "key_type is required for TABLE_DAT_KEY table"], false]}
FAILURE
Saving received results as /home/travis/build/droonga/droonga-engine/test/command/suite/groonga/table_create/dat-without-key-type.reject
--- (expected)
+++ (actual)
@@ -1,4 +1,115 @@
{
+ "error": {
+ "message": "failed to normalize response",
+ "detail": "undefined method `[]' for nil:NilClass (NoMethodError)",
+ "backtrace": [
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:101:in `normalize_groonga_command_response!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:39:in `normalize_droonga_message_body!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:34:in `normalize_droonga_message!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:27:in `normalize'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:156:in `normalize_response'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:134:in `clean_response'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:122:in `block in execute_request'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:129:in `block in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:175:in `block (4 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:202:in `block (2 levels) in on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:200:in `feed_each'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:200:in `block in on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:207:in `call'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:207:in `on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:173:in `block (3 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:172:in `each'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:172:in `block (2 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:164:in `loop'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:164:in `block in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:163:in `catch'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:163:in `receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:128:in `receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:67:in `block in request'"
+ ],
+ "response": {
+ "inReplyTo": "1426665663.3586223",
+ "statusCode": 200,
+ "type": "table_create.result",
+ "body": null
+ }
+ }
+}
+{
+ "error": {
+ "message": "failed to normalize response",
+ "detail": "undefined method `[]' for nil:NilClass (NoMethodError)",
+ "backtrace": [
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:101:in `normalize_groonga_command_response!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:39:in `normalize_droonga_message_body!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:34:in `normalize_droonga_message!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:27:in `normalize'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:156:in `normalize_response'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:134:in `clean_response'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:122:in `block in execute_request'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:129:in `block in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:175:in `block (4 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:202:in `block (2 levels) in on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:200:in `feed_each'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:200:in `block in on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:207:in `call'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:207:in `on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:173:in `block (3 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:172:in `each'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:172:in `block (2 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:164:in `loop'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:164:in `block in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:163:in `catch'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:163:in `receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:128:in `receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:67:in `block in request'"
+ ],
+ "response": {
+ "inReplyTo": "1426665663.3586223",
+ "statusCode": 200,
+ "type": "table_create.result",
+ "body": null
+ }
+ }
+}
+{
+ "error": {
+ "message": "failed to normalize response",
+ "detail": "undefined method `[]' for nil:NilClass (NoMethodError)",
+ "backtrace": [
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:101:in `normalize_groonga_command_response!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:39:in `normalize_droonga_message_body!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:34:in `normalize_droonga_message!'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/response-normalizer.rb:27:in `normalize'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:156:in `normalize_response'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:134:in `clean_response'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/drntest-3b6aed4f3533/lib/drntest/test-executor.rb:122:in `block in execute_request'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:129:in `block in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:175:in `block (4 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:202:in `block (2 levels) in on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:200:in `feed_each'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:200:in `block in on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:207:in `call'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:207:in `on_readable'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:173:in `block (3 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:172:in `each'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:172:in `block (2 levels) in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:164:in `loop'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:164:in `block in receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:163:in `catch'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:163:in `receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:128:in `receive'",
+ "/home/travis/.rvm/gems/ruby-1.9.3-p551/bundler/gems/droonga-client-ruby-4a58b5b186eb/lib/droonga/client/connection/droonga-protocol/thread.rb:67:in `block in request'"
+ ],
+ "response": {
+ "inReplyTo": "1426665663.3586223",
+ "statusCode": 200,
+ "type": "table_create.result",
+ "body": null
+ }
+ }
+}
+{
"inReplyTo": "request-id",
"statusCode": 200,
"type": "table_create.result",
~~~

**Comment by piroor** [comment]
Build #1101 - droonga/droonga-engine

 * Ruby: 2.0.0 test:command:default [stalled]

First failed:

~~~
watch/unsubscribe.test: 2015-03-18T07:55:45+00:00[4347][error]: serf-agent[4350]: memberlist: Failed to receive remote state: EOF
2015-03-18T07:55:46+00:00[4355][error]: dispatcher: no steps error: id=127.0.0.1:56944/droonga.#0, message={"id"=>"127.0.0.1:56944/droonga.#0", "input"=>"result", "value"=>true}
FAILURE
Saving received results as /home/travis/build/droonga/droonga-engine/test/command/suite/watch/unsubscribe.reject
--- (expected)
+++ (actual)
@@ -2,5 +2,11 @@
"inReplyTo": "request-id",
"statusCode": 200,
"type": "watch.unsubscribe.result",
- "body": true
+ "body": null
+}
+{
+ "inReplyTo": "request-id",
+ "statusCode": 200,
+ "type": "watch.unsubscribe.result",
+ "body": null
}
~~~

Second failed:

~~~
watch/subscribe.test: 2015-03-18T07:55:51+00:00[4425][error]: serf-agent[4428]: memberlist: Failed to receive remote state: EOF
2015-03-18T07:55:51+00:00[4433][error]: dispatcher: no steps error: id=127.0.0.1:59478/droonga.#0, message={"id"=>"127.0.0.1:59478/droonga.#0", "input"=>"result", "value"=>true}
FAILURE
Saving received results as /home/travis/build/droonga/droonga-engine/test/command/suite/watch/subscribe.reject
--- (expected)
+++ (actual)
@@ -2,5 +2,11 @@
"inReplyTo": "request-id",
"statusCode": 200,
"type": "watch.subscribe.result",
- "body": true
+ "body": null
+}
+{
+ "inReplyTo": "request-id",
+ "statusCode": 200,
+ "type": "watch.subscribe.result",
+ "body": null
}
~~~

And stalled:


~~~
system/status.test: 2015-03-18T07:55:56+00:00[4502][error]: serf-agent[4505]: memberlist: Failed to receive remote state: EOF
2015-03-18T07:55:57+00:00[4510][error]: dispatcher: there is no node to dispath a read message! my_role="service-provider" all_nodes=[{"name"=>"127.0.0.1:23003/droonga", "role"=>nil, "live"=>nil, "status"=>"dead"}]
NO RESPONSE
~~~

These three tests are the initial tree tests. In other words, this case initially failed.

**Comment by piroor** [comment]
@kou 

> Can we drop command version 1?

If Mori-san doesn't use version 1 catalog anymore, it's good time to drop it.

**Comment by piroor** [comment]
Build #1101 Ruby 2.1.0 test:command:default [stalled]

~~~
watch/unsubscribe.test: 2015-03-18T07:56:23+00:00[4345][error]: serf-agent[4348]: memberlist: Failed to receive remote state: EOF
SUCCESS
watch/subscribe.test: 2015-03-18T07:56:29+00:00[4425][error]: serf-agent[4428]: memberlist: Failed to receive remote state: EOF
SUCCESS
dump/column/index.test: 2015-03-18T07:56:34+00:00[4501][error]: serf-agent[4504]: memberlist: Failed to receive remote state: EOF
2015-03-18T07:56:35+00:00[4506][error]: dispatcher: there is no node to dispath a read message! my_role="service-provider" all_nodes=[{"name"=>"127.0.0.1:23003/droonga", "role"=>nil, "live"=>nil, "status"=>"dead"}]
NO RESPONSE
~~~

Initial two tests are succeeded but the third test is stalled.
Both two succeeded tests are failed on Ruby 2.0.0 environment.

**Comment by piroor** [comment]
OK, I've got it. Because the initialization of the cluster information via Serf was not guaranteed to be finished before running tests, many tests failed at random. (When tests were started before cluster information was initialized, the dispatcher couldn't find out the target live node for dispatching messages.)

**Comment by piroor** [comment]
Because tests are started correctly after cluster information is successfully initialized, now there are "green" results. https://travis-ci.org/droonga/droonga-engine/builds/55001022 (However, still there are failed and stalled tests...)

**Comment by piroor** [comment]
Because I introduced a cluster state mechanism based on Serf's cluster information, we had to start various initialization steps after the cluster information is correctly initiated. After the order of initialization processes are fixed to "initiate Serf agent" => "initiate the cluster information" => "start droonga-engine-service and worker processes", all tests seem to be executed correctly.
https://travis-ci.org/droonga/droonga-engine/builds/55124825

**Comment by piroor** [comment]
Verified that all results are green.
